blueprint:
  name: Update radiator valve offset
  description: >
    Version 1.
    Automatically updates the radiator valve offset based on room temperature
    and radiator temperature.
  domain: automation
  input:
    climate_entity:
      name: Radiator Climate Entity
      description: The climate entity of the radiator valve.
      selector:
        entity:
          domain: climate
    room_temperature_sensor:
      name: Room Temperature Sensor
      description: The sensor providing the calibrated room temperature.
      selector:
        entity:
          domain: sensor
    radiator_offset_number:
      name: Radiator Offset Number
      description: The number entity for the radiator valve offset.
      selector:
        entity:
          domain: number

trigger:
  - platform: state
    entity_id: !input room_temperature_sensor
  - platform: state
    entity_id: !input climate_entity

condition: []

action:
  - variables:
      room_temperature_sensor_entity: !input room_temperature_sensor
      radiator_climate_entity: !input climate_entity
      radiator_temperature_offset_number_entity: !input radiator_offset_number
  - service: logbook.log
    data:
      entity_id: automation.update_radiator_valve_offset_blueprint
      name: Update Radiator Valve Offset
      message: >-
        {% set room_temperature = states(room_temperature_sensor_entity) | float %}
        {% set radiator_temperature = state_attr(climate_entity, 'current_temperature') | float %}
        {% set radiator_temperature_offset = states(radiator_temperature_offset_number_entity) | float %}
        {% set new_radiator_temperature_offset = room_temperature - (radiator_temperature - radiator_temperature_offset) %}
        New offset {{ new_radiator_temperature_offset }}.
        Calculated from room temperature {{ room_temperature }},
        radiator temperature {{ radiator_temperature }},
        radiator temperature offset {{ radiator_temperature_offset }}
        [{{ room_temperature }} - ({{ radiator_temperature }} - {{ radiator_temperature_offset }})]
  - service: number.set_value
    target:
      entity_id: !input radiator_offset_number
    data:
      value: >-
        {% set room_temperature = states(room_temperature_sensor_entity) | float %}
        {% set radiator_temperature = state_attr(climate_entity, 'current_temperature') | float %}
        {% set radiator_temperature_offset = states(radiator_temperature_offset_number_entity) | float %}
        {% set new_radiator_temperature_offset = room_temperature - (radiator_temperature - radiator_temperature_offset) %}
        {{ new_radiator_temperature_offset }}

mode: single
